// This file is auto-generated by @hey-api/openapi-ts

export const AssigneeBriefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'email'],
    title: 'AssigneeBrief'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DepartmentBriefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'DepartmentBrief'
} as const;

export const DepartmentCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'DepartmentCreate'
} as const;

export const DepartmentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'sort_order', 'created_at'],
    title: 'DepartmentPublic'
} as const;

export const DepartmentReorderSchema = {
    properties: {
        ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Ids'
        }
    },
    type: 'object',
    required: ['ids'],
    title: 'DepartmentReorder',
    description: '按数组顺序重排部门 sort_order'
} as const;

export const DepartmentStatsSchema = {
    properties: {
        department: {
            '$ref': '#/components/schemas/DepartmentBrief'
        },
        member_count: {
            type: 'integer',
            title: 'Member Count'
        },
        kr_count: {
            type: 'integer',
            title: 'Kr Count'
        },
        avg_progress: {
            type: 'integer',
            title: 'Avg Progress'
        },
        objective_count: {
            type: 'integer',
            title: 'Objective Count'
        },
        objectives: {
            items: {
                '$ref': '#/components/schemas/ObjectiveKrsGroup'
            },
            type: 'array',
            title: 'Objectives'
        }
    },
    type: 'object',
    required: ['department', 'member_count', 'kr_count', 'avg_progress', 'objective_count', 'objectives'],
    title: 'DepartmentStats'
} as const;

export const DepartmentStatsListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DepartmentStats'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'DepartmentStatsList'
} as const;

export const DepartmentUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'DepartmentUpdate'
} as const;

export const DepartmentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DepartmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DepartmentsPublic'
} as const;

export const DetailCountsSchema = {
    properties: {
        work_plans: {
            type: 'integer',
            title: 'Work Plans'
        },
        task_summaries: {
            type: 'integer',
            title: 'Task Summaries'
        },
        work_reviews: {
            type: 'integer',
            title: 'Work Reviews'
        }
    },
    type: 'object',
    required: ['work_plans', 'task_summaries', 'work_reviews'],
    title: 'DetailCounts'
} as const;

export const FeishuTicketExchangeSchema = {
    properties: {
        ticket: {
            type: 'string',
            maxLength: 255,
            minLength: 32,
            title: 'Ticket'
        }
    },
    type: 'object',
    required: ['ticket'],
    title: 'FeishuTicketExchange'
} as const;

export const FieldConfigPublicSchema = {
    properties: {
        section: {
            type: 'string',
            title: 'Section'
        },
        field_key: {
            type: 'string',
            title: 'Field Key'
        },
        is_required: {
            type: 'boolean',
            title: 'Is Required'
        }
    },
    type: 'object',
    required: ['section', 'field_key', 'is_required'],
    title: 'FieldConfigPublic'
} as const;

export const FieldConfigUpdateSchema = {
    properties: {
        section: {
            type: 'string',
            maxLength: 32,
            title: 'Section'
        },
        field_key: {
            type: 'string',
            maxLength: 64,
            title: 'Field Key'
        },
        is_required: {
            type: 'boolean',
            title: 'Is Required'
        }
    },
    type: 'object',
    required: ['section', 'field_key', 'is_required'],
    title: 'FieldConfigUpdate'
} as const;

export const FieldConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FieldConfigPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'FieldConfigsPublic'
} as const;

export const FieldConfigsUpdateSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FieldConfigUpdate'
            },
            type: 'array',
            maxItems: 20,
            minItems: 1,
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'FieldConfigsUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const KeyResultCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        deadline: {
            type: 'string',
            format: 'date',
            title: 'Deadline'
        },
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        objective_id: {
            type: 'string',
            format: 'uuid',
            title: 'Objective Id'
        },
        assignee_id: {
            type: 'string',
            format: 'uuid',
            title: 'Assignee Id'
        }
    },
    type: 'object',
    required: ['title', 'start_date', 'deadline', 'objective_id', 'assignee_id'],
    title: 'KeyResultCreate'
} as const;

export const KeyResultProgressUpdateSchema = {
    properties: {
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress'
        }
    },
    type: 'object',
    required: ['progress'],
    title: 'KeyResultProgressUpdate',
    description: '成员更新自己 KR 进度的专用 schema——只放行 progress 字段'
} as const;

export const KeyResultPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        deadline: {
            type: 'string',
            format: 'date',
            title: 'Deadline'
        },
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        objective_id: {
            type: 'string',
            format: 'uuid',
            title: 'Objective Id'
        },
        assignee: {
            '$ref': '#/components/schemas/AssigneeBrief'
        },
        department: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DepartmentBrief'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'start_date', 'deadline', 'id', 'objective_id', 'assignee', 'created_at', 'updated_at'],
    title: 'KeyResultPublic'
} as const;

export const KeyResultUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        deadline: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deadline'
        },
        progress: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        objective_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Objective Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        }
    },
    type: 'object',
    title: 'KeyResultUpdate'
} as const;

export const KeyResultsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/KeyResultPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'KeyResultsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        notification_type: {
            type: 'string',
            title: 'Notification Type'
        },
        is_read: {
            type: 'boolean',
            title: 'Is Read'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'content', 'notification_type', 'is_read', 'created_at', 'read_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotificationsPublic'
} as const;

export const ObjectiveCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ObjectiveCreate'
} as const;

export const ObjectiveKrsGroupSchema = {
    properties: {
        objective_id: {
            type: 'string',
            format: 'uuid',
            title: 'Objective Id'
        },
        objective_title: {
            type: 'string',
            title: 'Objective Title'
        },
        krs: {
            items: {
                '$ref': '#/components/schemas/KeyResultPublic'
            },
            type: 'array',
            title: 'Krs'
        }
    },
    type: 'object',
    required: ['objective_id', 'objective_title', 'krs'],
    title: 'ObjectiveKrsGroup',
    description: '部门视角：某个 Objective 下属于该部门的 KR'
} as const;

export const ObjectivePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        progress: {
            type: 'integer',
            title: 'Progress',
            default: 0
        },
        kr_count: {
            type: 'integer',
            title: 'Kr Count',
            default: 0
        },
        time_range: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ObjectiveTimeRange'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'id', 'created_by_id', 'created_at', 'updated_at'],
    title: 'ObjectivePublic'
} as const;

export const ObjectiveTimeRangeSchema = {
    properties: {
        start: {
            type: 'string',
            format: 'date',
            title: 'Start'
        },
        end: {
            type: 'string',
            format: 'date',
            title: 'End'
        }
    },
    type: 'object',
    required: ['start', 'end'],
    title: 'ObjectiveTimeRange',
    description: '由 KR 计算出的时间范围；无 KR 时为 null'
} as const;

export const ObjectiveUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ObjectiveUpdate'
} as const;

export const ObjectivesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ObjectivePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ObjectivesPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ReminderDeliveryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        user_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        attempts: {
            type: 'integer',
            title: 'Attempts'
        },
        error_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Code'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        sent_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sent At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'user_name', 'status', 'attempts', 'error_code', 'error_message', 'sent_at'],
    title: 'ReminderDeliveryPublic'
} as const;

export const ReminderRecipientSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        is_feishu_linked: {
            type: 'boolean',
            title: 'Is Feishu Linked'
        }
    },
    type: 'object',
    required: ['id', 'name', 'email', 'department_id', 'is_feishu_linked'],
    title: 'ReminderRecipient'
} as const;

export const ReminderRecipientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReminderRecipient'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ReminderRecipientsPublic'
} as const;

export const ReminderRuleInputSchema = {
    properties: {
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        weekday: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 7,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weekday'
        },
        month_day: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 31,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Month Day'
        },
        is_last_day: {
            type: 'boolean',
            title: 'Is Last Day',
            default: false
        },
        local_time: {
            type: 'string',
            format: 'time',
            title: 'Local Time'
        },
        timezone: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Timezone',
            default: 'Asia/Shanghai'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        recipient_user_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Recipient User Ids'
        }
    },
    type: 'object',
    required: ['report_type', 'local_time', 'recipient_user_ids'],
    title: 'ReminderRuleInput'
} as const;

export const ReminderRulePublicSchema = {
    properties: {
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        weekday: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 7,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weekday'
        },
        month_day: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 31,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Month Day'
        },
        is_last_day: {
            type: 'boolean',
            title: 'Is Last Day',
            default: false
        },
        local_time: {
            type: 'string',
            format: 'time',
            title: 'Local Time'
        },
        timezone: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Timezone',
            default: 'Asia/Shanghai'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        recipient_user_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Recipient User Ids'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['report_type', 'local_time', 'id', 'created_by_id', 'created_at', 'updated_at'],
    title: 'ReminderRulePublic'
} as const;

export const ReminderRulesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReminderRulePublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ReminderRulesPublic'
} as const;

export const ReminderRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        rule_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rule Id'
        },
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        period_start: {
            type: 'string',
            format: 'date',
            title: 'Period Start'
        },
        period_end: {
            type: 'string',
            format: 'date',
            title: 'Period End'
        },
        scheduled_for: {
            type: 'string',
            format: 'date-time',
            title: 'Scheduled For'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        target_count: {
            type: 'integer',
            title: 'Target Count'
        },
        sent_count: {
            type: 'integer',
            title: 'Sent Count'
        },
        failed_count: {
            type: 'integer',
            title: 'Failed Count'
        },
        skipped_count: {
            type: 'integer',
            title: 'Skipped Count'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        deliveries: {
            items: {
                '$ref': '#/components/schemas/ReminderDeliveryPublic'
            },
            type: 'array',
            title: 'Deliveries'
        }
    },
    type: 'object',
    required: ['id', 'rule_id', 'report_type', 'period_start', 'period_end', 'scheduled_for', 'status', 'target_count', 'sent_count', 'failed_count', 'skipped_count', 'created_at', 'finished_at', 'deliveries'],
    title: 'ReminderRunPublic'
} as const;

export const ReminderRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReminderRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReminderRunsPublic'
} as const;

export const ReminderTestRecipientSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['id', 'name', 'email'],
    title: 'ReminderTestRecipient'
} as const;

export const ReminderTestRecipientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReminderTestRecipient'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ReminderTestRecipientsPublic'
} as const;

export const ReminderTestRequestSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        }
    },
    type: 'object',
    required: ['user_id'],
    title: 'ReminderTestRequest'
} as const;

export const ReminderTestResultSchema = {
    properties: {
        message_id: {
            type: 'string',
            title: 'Message Id'
        }
    },
    type: 'object',
    required: ['message_id'],
    title: 'ReminderTestResult'
} as const;

export const ReminderTimezonesPublicSchema = {
    properties: {
        data: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'ReminderTimezonesPublic'
} as const;

export const ReminderUnboundUserSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        }
    },
    type: 'object',
    required: ['id', 'name', 'email', 'is_superuser'],
    title: 'ReminderUnboundUser'
} as const;

export const ReminderUnboundUsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ReminderUnboundUser'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ReminderUnboundUsersPublic'
} as const;

export const ReportTypeSchema = {
    type: 'string',
    enum: ['weekly', 'monthly'],
    title: 'ReportType'
} as const;

export const ReporterBriefSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['id', 'name', 'email'],
    title: 'ReporterBrief'
} as const;

export const TaskSummaryInputSchema = {
    properties: {
        work_goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Goal'
        },
        completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completion Date'
        },
        progress_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress Description'
        },
        progress: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        incomplete_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Incomplete Reason'
        }
    },
    type: 'object',
    title: 'TaskSummaryInput'
} as const;

export const TaskSummaryPublicSchema = {
    properties: {
        work_goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Work Goal'
        },
        completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completion Date'
        },
        progress_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress Description'
        },
        progress: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        incomplete_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Incomplete Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        }
    },
    type: 'object',
    required: ['id', 'sort_order'],
    title: 'TaskSummaryPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UnreadCountResponseSchema = {
    properties: {
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['count'],
    title: 'UnreadCountResponse'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        language: {
            type: 'string',
            maxLength: 10,
            title: 'Language',
            default: 'zh'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        language: {
            type: 'string',
            maxLength: 10,
            title: 'Language',
            default: 'zh'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        is_feishu_user: {
            type: 'boolean',
            title: 'Is Feishu User',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'email'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserStatsSchema = {
    properties: {
        user: {
            '$ref': '#/components/schemas/AssigneeBrief'
        },
        department: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DepartmentBrief'
                },
                {
                    type: 'null'
                }
            ]
        },
        kr_count: {
            type: 'integer',
            title: 'Kr Count'
        },
        avg_progress: {
            type: 'integer',
            title: 'Avg Progress'
        },
        krs: {
            items: {
                '$ref': '#/components/schemas/KeyResultPublic'
            },
            type: 'array',
            title: 'Krs'
        }
    },
    type: 'object',
    required: ['user', 'department', 'kr_count', 'avg_progress', 'krs'],
    title: 'UserStats'
} as const;

export const UserStatsListSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserStats'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'UserStatsList'
} as const;

export const UserUpdateSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        language: {
            type: 'string',
            maxLength: 10,
            title: 'Language',
            default: 'zh'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkPlanInputSchema = {
    properties: {
        plan_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plan Content'
        },
        planned_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planned Completion Date'
        },
        expected_result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Result'
        },
        support_needed: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Support Needed'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        }
    },
    type: 'object',
    title: 'WorkPlanInput'
} as const;

export const WorkPlanPublicSchema = {
    properties: {
        plan_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plan Content'
        },
        planned_completion_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Planned Completion Date'
        },
        expected_result: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expected Result'
        },
        support_needed: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Support Needed'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        }
    },
    type: 'object',
    required: ['id', 'sort_order'],
    title: 'WorkPlanPublic'
} as const;

export const WorkReportDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        reporter: {
            '$ref': '#/components/schemas/ReporterBrief'
        },
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        period_start: {
            type: 'string',
            format: 'date',
            title: 'Period Start'
        },
        period_end: {
            type: 'string',
            format: 'date',
            title: 'Period End'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        submitted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Submitted At'
        },
        counts: {
            '$ref': '#/components/schemas/DetailCounts'
        },
        work_plans: {
            items: {
                '$ref': '#/components/schemas/WorkPlanPublic'
            },
            type: 'array',
            title: 'Work Plans'
        },
        task_summaries: {
            items: {
                '$ref': '#/components/schemas/TaskSummaryPublic'
            },
            type: 'array',
            title: 'Task Summaries'
        },
        work_reviews: {
            items: {
                '$ref': '#/components/schemas/WorkReviewPublic'
            },
            type: 'array',
            title: 'Work Reviews'
        }
    },
    type: 'object',
    required: ['id', 'reporter', 'report_type', 'period_start', 'period_end', 'title', 'remarks', 'submitted_at', 'counts', 'work_plans', 'task_summaries', 'work_reviews'],
    title: 'WorkReportDetail'
} as const;

export const WorkReportSubmissionResultSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        reporter: {
            '$ref': '#/components/schemas/ReporterBrief'
        },
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        period_start: {
            type: 'string',
            format: 'date',
            title: 'Period Start'
        },
        period_end: {
            type: 'string',
            format: 'date',
            title: 'Period End'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        submitted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Submitted At'
        },
        submission_mode: {
            type: 'string',
            enum: ['created', 'supplemented'],
            title: 'Submission Mode'
        },
        counts: {
            '$ref': '#/components/schemas/DetailCounts'
        }
    },
    type: 'object',
    required: ['id', 'reporter', 'report_type', 'period_start', 'period_end', 'title', 'remarks', 'submitted_at', 'submission_mode', 'counts'],
    title: 'WorkReportSubmissionResult'
} as const;

export const WorkReportSubmitSchema = {
    properties: {
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        period_key: {
            type: 'string',
            maxLength: 8,
            minLength: 7,
            title: 'Period Key'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        work_plans: {
            items: {
                '$ref': '#/components/schemas/WorkPlanInput'
            },
            type: 'array',
            maxItems: 100,
            title: 'Work Plans'
        },
        task_summaries: {
            items: {
                '$ref': '#/components/schemas/TaskSummaryInput'
            },
            type: 'array',
            maxItems: 100,
            title: 'Task Summaries'
        },
        work_reviews: {
            items: {
                '$ref': '#/components/schemas/WorkReviewInput'
            },
            type: 'array',
            maxItems: 100,
            title: 'Work Reviews'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['report_type', 'period_key', 'title'],
    title: 'WorkReportSubmit'
} as const;

export const WorkReportSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        reporter: {
            '$ref': '#/components/schemas/ReporterBrief'
        },
        report_type: {
            '$ref': '#/components/schemas/ReportType'
        },
        period_start: {
            type: 'string',
            format: 'date',
            title: 'Period Start'
        },
        period_end: {
            type: 'string',
            format: 'date',
            title: 'Period End'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        remarks: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remarks'
        },
        submitted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Submitted At'
        },
        counts: {
            '$ref': '#/components/schemas/DetailCounts'
        }
    },
    type: 'object',
    required: ['id', 'reporter', 'report_type', 'period_start', 'period_end', 'title', 'remarks', 'submitted_at', 'counts'],
    title: 'WorkReportSummary'
} as const;

export const WorkReportsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkReportSummary'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkReportsPublic'
} as const;

export const WorkReviewInputSchema = {
    properties: {
        review_module: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Module'
        },
        review_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Content'
        }
    },
    type: 'object',
    title: 'WorkReviewInput'
} as const;

export const WorkReviewPublicSchema = {
    properties: {
        review_module: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Module'
        },
        review_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Review Content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order'
        }
    },
    type: 'object',
    required: ['id', 'sort_order'],
    title: 'WorkReviewPublic'
} as const;