// This file is auto-generated by @hey-api/openapi-ts

export type AssigneeBrief = {
    id: string;
    full_name: (string | null);
    email: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DepartmentBrief = {
    id: string;
    name: string;
};

export type DepartmentCreate = {
    name: string;
    description?: (string | null);
};

export type DepartmentPublic = {
    name: string;
    description?: (string | null);
    id: string;
    sort_order: number;
    created_at: string;
};

/**
 * 按数组顺序重排部门 sort_order
 */
export type DepartmentReorder = {
    ids: Array<(string)>;
};

export type DepartmentsPublic = {
    data: Array<DepartmentPublic>;
    count: number;
};

export type DepartmentStats = {
    department: DepartmentBrief;
    member_count: number;
    kr_count: number;
    avg_progress: number;
    objective_count: number;
    objectives: Array<ObjectiveKrsGroup>;
};

export type DepartmentStatsList = {
    data: Array<DepartmentStats>;
};

export type DepartmentUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KeyResultCreate = {
    title: string;
    description?: (string | null);
    start_date: string;
    deadline: string;
    progress?: number;
    objective_id: string;
    assignee_id: string;
};

/**
 * 成员更新自己 KR 进度的专用 schema——只放行 progress 字段
 */
export type KeyResultProgressUpdate = {
    progress: number;
};

export type KeyResultPublic = {
    title: string;
    description?: (string | null);
    start_date: string;
    deadline: string;
    progress?: number;
    id: string;
    objective_id: string;
    assignee: AssigneeBrief;
    department?: (DepartmentBrief | null);
    created_at: string;
    updated_at: string;
};

export type KeyResultsPublic = {
    data: Array<KeyResultPublic>;
    count: number;
};

export type KeyResultUpdate = {
    title?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    deadline?: (string | null);
    progress?: (number | null);
    objective_id?: (string | null);
    assignee_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    id: string;
    title: string;
    content: string;
    notification_type: string;
    is_read: boolean;
    created_at: string;
    read_at: (string | null);
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

export type ObjectiveCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 部门视角：某个 Objective 下属于该部门的 KR
 */
export type ObjectiveKrsGroup = {
    objective_id: string;
    objective_title: string;
    krs: Array<KeyResultPublic>;
};

export type ObjectivePublic = {
    title: string;
    description?: (string | null);
    id: string;
    created_by_id: string;
    created_at: string;
    updated_at: string;
    progress?: number;
    kr_count?: number;
    time_range?: (ObjectiveTimeRange | null);
};

export type ObjectivesPublic = {
    data: Array<ObjectivePublic>;
    count: number;
};

/**
 * 由 KR 计算出的时间范围；无 KR 时为 null
 */
export type ObjectiveTimeRange = {
    start: string;
    end: string;
};

export type ObjectiveUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnreadCountResponse = {
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    id?: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    password: string;
};

export type UserPublic = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStats = {
    user: AssigneeBrief;
    department: (DepartmentBrief | null);
    kr_count: number;
    avg_progress: number;
    krs: Array<KeyResultPublic>;
};

export type UserStatsList = {
    data: Array<UserStats>;
};

export type UserUpdate = {
    id?: (string | null);
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    language?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsListNotificationsEndpointData = {
    /**
     * 筛选已读/未读
     */
    isRead?: (boolean | null);
    limit?: number;
    page?: number;
};

export type NotificationsListNotificationsEndpointResponse = (NotificationsPublic);

export type NotificationsMarkReadEndpointData = {
    notificationId: string;
};

export type NotificationsMarkReadEndpointResponse = (NotificationPublic);

export type NotificationsMarkAllReadEndpointResponse = ({
    [key: string]: unknown;
});

export type NotificationsDeleteNotificationEndpointData = {
    notificationId: string;
};

export type NotificationsDeleteNotificationEndpointResponse = (void);

export type NotificationsUnreadCountEndpointResponse = (UnreadCountResponse);

export type OkrReadDepartmentsResponse = (DepartmentsPublic);

export type OkrCreateDepartmentData = {
    requestBody: DepartmentCreate;
};

export type OkrCreateDepartmentResponse = (DepartmentPublic);

export type OkrUpdateDepartmentData = {
    departmentId: string;
    requestBody: DepartmentUpdate;
};

export type OkrUpdateDepartmentResponse = (DepartmentPublic);

export type OkrDeleteDepartmentData = {
    departmentId: string;
};

export type OkrDeleteDepartmentResponse = (Message);

export type OkrReorderDepartmentsData = {
    requestBody: DepartmentReorder;
};

export type OkrReorderDepartmentsResponse = (Message);

export type OkrReadObjectivesResponse = (ObjectivesPublic);

export type OkrCreateObjectiveData = {
    requestBody: ObjectiveCreate;
};

export type OkrCreateObjectiveResponse = (ObjectivePublic);

export type OkrUpdateObjectiveData = {
    objectiveId: string;
    requestBody: ObjectiveUpdate;
};

export type OkrUpdateObjectiveResponse = (ObjectivePublic);

export type OkrDeleteObjectiveData = {
    objectiveId: string;
};

export type OkrDeleteObjectiveResponse = (Message);

export type OkrReadObjectiveKrsData = {
    objectiveId: string;
};

export type OkrReadObjectiveKrsResponse = (KeyResultsPublic);

export type OkrCreateKeyResultData = {
    requestBody: KeyResultCreate;
};

export type OkrCreateKeyResultResponse = (KeyResultPublic);

export type OkrUpdateKeyResultData = {
    krId: string;
    requestBody: KeyResultUpdate;
};

export type OkrUpdateKeyResultResponse = (KeyResultPublic);

export type OkrDeleteKeyResultData = {
    krId: string;
};

export type OkrDeleteKeyResultResponse = (Message);

export type OkrReadMyKrsData = {
    filter?: 'all' | 'active' | 'done' | 'due_soon' | 'overdue';
};

export type OkrReadMyKrsResponse = (KeyResultsPublic);

export type OkrUpdateKrProgressData = {
    krId: string;
    requestBody: KeyResultProgressUpdate;
};

export type OkrUpdateKrProgressResponse = (KeyResultPublic);

export type OkrReadStatsByDepartmentResponse = (DepartmentStatsList);

export type OkrReadStatsByUserResponse = (UserStatsList);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublicGetPublicStatsResponse = ({
    [key: string]: (number);
});

export type UsersReadUsersData = {
    limit?: number;
    /**
     * Search by name or email
     */
    q?: (string | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsStorageInfoEndpointResponse = ({
    [key: string]: unknown;
});