// This file is auto-generated by @hey-api/openapi-ts

export type AssigneeBrief = {
    id: string;
    full_name: (string | null);
    email: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DepartmentBrief = {
    id: string;
    name: string;
};

export type DepartmentCreate = {
    name: string;
    description?: (string | null);
};

export type DepartmentPublic = {
    name: string;
    description?: (string | null);
    id: string;
    sort_order: number;
    created_at: string;
};

/**
 * 按数组顺序重排部门 sort_order
 */
export type DepartmentReorder = {
    ids: Array<(string)>;
};

export type DepartmentsPublic = {
    data: Array<DepartmentPublic>;
    count: number;
};

export type DepartmentStats = {
    department: DepartmentBrief;
    member_count: number;
    kr_count: number;
    avg_progress: number;
    objective_count: number;
    objectives: Array<ObjectiveKrsGroup>;
};

export type DepartmentStatsList = {
    data: Array<DepartmentStats>;
};

export type DepartmentUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type DetailCounts = {
    work_plans: number;
    task_summaries: number;
    work_reviews: number;
};

export type FeishuTicketExchange = {
    ticket: string;
};

export type FieldConfigPublic = {
    section: string;
    field_key: string;
    is_required: boolean;
};

export type FieldConfigsPublic = {
    data: Array<FieldConfigPublic>;
};

export type FieldConfigsUpdate = {
    data: Array<FieldConfigUpdate>;
};

export type FieldConfigUpdate = {
    section: string;
    field_key: string;
    is_required: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type KeyResultCreate = {
    title: string;
    description?: (string | null);
    start_date: string;
    deadline: string;
    progress?: number;
    objective_id: string;
    assignee_id: string;
};

/**
 * 成员更新自己 KR 进度的专用 schema——只放行 progress 字段
 */
export type KeyResultProgressUpdate = {
    progress: number;
};

export type KeyResultPublic = {
    title: string;
    description?: (string | null);
    start_date: string;
    deadline: string;
    progress?: number;
    id: string;
    objective_id: string;
    assignee: AssigneeBrief;
    department?: (DepartmentBrief | null);
    created_at: string;
    updated_at: string;
};

export type KeyResultsPublic = {
    data: Array<KeyResultPublic>;
    count: number;
};

export type KeyResultUpdate = {
    title?: (string | null);
    description?: (string | null);
    start_date?: (string | null);
    deadline?: (string | null);
    progress?: (number | null);
    objective_id?: (string | null);
    assignee_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    id: string;
    title: string;
    content: string;
    notification_type: string;
    is_read: boolean;
    created_at: string;
    read_at: (string | null);
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

export type ObjectiveCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 部门视角：某个 Objective 下属于该部门的 KR
 */
export type ObjectiveKrsGroup = {
    objective_id: string;
    objective_title: string;
    krs: Array<KeyResultPublic>;
};

export type ObjectivePublic = {
    title: string;
    description?: (string | null);
    id: string;
    created_by_id: string;
    created_at: string;
    updated_at: string;
    progress?: number;
    kr_count?: number;
    time_range?: (ObjectiveTimeRange | null);
};

export type ObjectivesPublic = {
    data: Array<ObjectivePublic>;
    count: number;
};

/**
 * 由 KR 计算出的时间范围；无 KR 时为 null
 */
export type ObjectiveTimeRange = {
    start: string;
    end: string;
};

export type ObjectiveUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReminderDeliveryPublic = {
    id: string;
    user_id: (string | null);
    user_name: (string | null);
    status: string;
    attempts: number;
    error_code: (string | null);
    error_message: (string | null);
    sent_at: (string | null);
};

export type ReminderRecipient = {
    id: string;
    name: (string | null);
    email: string;
    department_id: (string | null);
    is_feishu_linked: boolean;
};

export type ReminderRecipientsPublic = {
    data: Array<ReminderRecipient>;
};

export type ReminderRuleInput = {
    report_type: ReportType;
    weekday?: (number | null);
    month_day?: (number | null);
    is_last_day?: boolean;
    local_time: string;
    timezone?: string;
    enabled?: boolean;
    recipient_user_ids: Array<(string)>;
};

export type ReminderRulePublic = {
    report_type: ReportType;
    weekday?: (number | null);
    month_day?: (number | null);
    is_last_day?: boolean;
    local_time: string;
    timezone?: string;
    enabled?: boolean;
    recipient_user_ids?: Array<(string)>;
    id: string;
    created_by_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type ReminderRulesPublic = {
    data: Array<ReminderRulePublic>;
};

export type ReminderRunPublic = {
    id: string;
    rule_id: (string | null);
    report_type: ReportType;
    period_start: string;
    period_end: string;
    scheduled_for: string;
    status: string;
    target_count: number;
    sent_count: number;
    failed_count: number;
    skipped_count: number;
    created_at: string;
    finished_at: (string | null);
    deliveries: Array<ReminderDeliveryPublic>;
};

export type ReminderRunsPublic = {
    data: Array<ReminderRunPublic>;
    count: number;
};

export type ReminderTestRecipient = {
    id: string;
    name: (string | null);
    email: string;
};

export type ReminderTestRecipientsPublic = {
    data: Array<ReminderTestRecipient>;
};

export type ReminderTestRequest = {
    user_id: string;
};

export type ReminderTestResult = {
    message_id: string;
};

export type ReminderTimezonesPublic = {
    data: Array<(string)>;
};

export type ReminderUnboundUser = {
    id: string;
    name: (string | null);
    email: string;
    is_superuser: boolean;
};

export type ReminderUnboundUsersPublic = {
    data: Array<ReminderUnboundUser>;
    count: number;
};

export type ReporterBrief = {
    id: (string | null);
    name: (string | null);
    email: string;
};

export type ReportType = 'weekly' | 'monthly';

export type TaskSummaryInput = {
    work_goal?: (string | null);
    completion_date?: (string | null);
    progress_description?: (string | null);
    progress?: (number | null);
    incomplete_reason?: (string | null);
};

export type TaskSummaryPublic = {
    work_goal?: (string | null);
    completion_date?: (string | null);
    progress_description?: (string | null);
    progress?: (number | null);
    incomplete_reason?: (string | null);
    id: string;
    sort_order: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnreadCountResponse = {
    count: number;
};

export type UpdatePassword = {
    current_password?: (string | null);
    new_password: string;
};

export type UserCreate = {
    id?: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    password: string;
};

export type UserPublic = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    created_at?: (string | null);
    is_feishu_user?: boolean;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserStats = {
    user: AssigneeBrief;
    department: (DepartmentBrief | null);
    kr_count: number;
    avg_progress: number;
    krs: Array<KeyResultPublic>;
};

export type UserStatsList = {
    data: Array<UserStats>;
};

export type UserUpdate = {
    id?: (string | null);
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    language?: string;
    department_id?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    language?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkPlanInput = {
    plan_content?: (string | null);
    planned_completion_date?: (string | null);
    expected_result?: (string | null);
    support_needed?: (string | null);
    remarks?: (string | null);
};

export type WorkPlanPublic = {
    plan_content?: (string | null);
    planned_completion_date?: (string | null);
    expected_result?: (string | null);
    support_needed?: (string | null);
    remarks?: (string | null);
    id: string;
    sort_order: number;
};

export type WorkReportDetail = {
    id: string;
    reporter: ReporterBrief;
    report_type: ReportType;
    period_start: string;
    period_end: string;
    title: string;
    remarks: (string | null);
    submitted_at: string;
    counts: DetailCounts;
    work_plans: Array<WorkPlanPublic>;
    task_summaries: Array<TaskSummaryPublic>;
    work_reviews: Array<WorkReviewPublic>;
};

export type WorkReportsPublic = {
    data: Array<WorkReportSummary>;
    count: number;
};

export type WorkReportSubmissionResult = {
    id: string;
    reporter: ReporterBrief;
    report_type: ReportType;
    period_start: string;
    period_end: string;
    title: string;
    remarks: (string | null);
    submitted_at: string;
    submission_mode: 'created' | 'supplemented';
    counts: DetailCounts;
};

export type submission_mode = 'created' | 'supplemented';

export type WorkReportSubmit = {
    report_type: ReportType;
    period_key: string;
    title: string;
    remarks?: (string | null);
    work_plans?: Array<WorkPlanInput>;
    task_summaries?: Array<TaskSummaryInput>;
    work_reviews?: Array<WorkReviewInput>;
};

export type WorkReportSummary = {
    id: string;
    reporter: ReporterBrief;
    report_type: ReportType;
    period_start: string;
    period_end: string;
    title: string;
    remarks: (string | null);
    submitted_at: string;
    counts: DetailCounts;
};

export type WorkReviewInput = {
    review_module?: (string | null);
    review_content?: (string | null);
};

export type WorkReviewPublic = {
    review_module?: (string | null);
    review_content?: (string | null);
    id: string;
    sort_order: number;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginFeishuLoginCallbackData = {
    code?: (string | null);
    error?: (string | null);
    feishuOauthState?: (string | null);
    state: string;
};

export type LoginExchangeFeishuLoginTicketData = {
    requestBody: FeishuTicketExchange;
};

export type LoginExchangeFeishuLoginTicketResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NotificationsListNotificationsEndpointData = {
    /**
     * 筛选已读/未读
     */
    isRead?: (boolean | null);
    limit?: number;
    page?: number;
};

export type NotificationsListNotificationsEndpointResponse = (NotificationsPublic);

export type NotificationsMarkReadEndpointData = {
    notificationId: string;
};

export type NotificationsMarkReadEndpointResponse = (NotificationPublic);

export type NotificationsMarkAllReadEndpointResponse = ({
    [key: string]: unknown;
});

export type NotificationsDeleteNotificationEndpointData = {
    notificationId: string;
};

export type NotificationsDeleteNotificationEndpointResponse = (void);

export type NotificationsUnreadCountEndpointResponse = (UnreadCountResponse);

export type OkrReadObjectivesResponse = (ObjectivesPublic);

export type OkrCreateObjectiveData = {
    requestBody: ObjectiveCreate;
};

export type OkrCreateObjectiveResponse = (ObjectivePublic);

export type OkrUpdateObjectiveData = {
    objectiveId: string;
    requestBody: ObjectiveUpdate;
};

export type OkrUpdateObjectiveResponse = (ObjectivePublic);

export type OkrDeleteObjectiveData = {
    objectiveId: string;
};

export type OkrDeleteObjectiveResponse = (Message);

export type OkrReadObjectiveKrsData = {
    objectiveId: string;
};

export type OkrReadObjectiveKrsResponse = (KeyResultsPublic);

export type OkrReadOverviewDepartmentsResponse = (DepartmentStatsList);

export type OkrReadOverviewMembersResponse = (UserStatsList);

export type OkrCreateKeyResultData = {
    requestBody: KeyResultCreate;
};

export type OkrCreateKeyResultResponse = (KeyResultPublic);

export type OkrUpdateKeyResultData = {
    krId: string;
    requestBody: KeyResultUpdate;
};

export type OkrUpdateKeyResultResponse = (KeyResultPublic);

export type OkrDeleteKeyResultData = {
    krId: string;
};

export type OkrDeleteKeyResultResponse = (Message);

export type OkrReadMyKrsData = {
    filter?: 'all' | 'active' | 'done' | 'due_soon' | 'overdue';
};

export type OkrReadMyKrsResponse = (KeyResultsPublic);

export type OkrUpdateKrProgressData = {
    krId: string;
    requestBody: KeyResultProgressUpdate;
};

export type OkrUpdateKrProgressResponse = (KeyResultPublic);

export type OkrReadDepartmentsResponse = (DepartmentsPublic);

export type OkrCreateDepartmentData = {
    requestBody: DepartmentCreate;
};

export type OkrCreateDepartmentResponse = (DepartmentPublic);

export type OkrUpdateDepartmentData = {
    departmentId: string;
    requestBody: DepartmentUpdate;
};

export type OkrUpdateDepartmentResponse = (DepartmentPublic);

export type OkrDeleteDepartmentData = {
    departmentId: string;
};

export type OkrDeleteDepartmentResponse = (Message);

export type OkrReorderDepartmentsData = {
    requestBody: DepartmentReorder;
};

export type OkrReorderDepartmentsResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PublicGetPublicStatsResponse = ({
    [key: string]: (number);
});

export type UsersReadUsersData = {
    limit?: number;
    /**
     * Search by name or email
     */
    q?: (string | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsStorageInfoEndpointResponse = ({
    [key: string]: unknown;
});

export type WorkReportsReadMyWorkReportsData = {
    keyword?: (string | null);
    limit?: number;
    periodFrom?: (string | null);
    periodTo?: (string | null);
    reportType?: (ReportType | null);
    skip?: number;
    submittedFrom?: (string | null);
    submittedTo?: (string | null);
};

export type WorkReportsReadMyWorkReportsResponse = (WorkReportsPublic);

export type WorkReportsReadAllWorkReportsData = {
    keyword?: (string | null);
    limit?: number;
    periodFrom?: (string | null);
    periodTo?: (string | null);
    reporter?: (string | null);
    reportType?: (ReportType | null);
    skip?: number;
    submittedFrom?: (string | null);
    submittedTo?: (string | null);
};

export type WorkReportsReadAllWorkReportsResponse = (WorkReportsPublic);

export type WorkReportsReadFieldConfigResponse = (FieldConfigsPublic);

export type WorkReportsUpdateFieldConfigData = {
    requestBody: FieldConfigsUpdate;
};

export type WorkReportsUpdateFieldConfigResponse = (FieldConfigsPublic);

export type WorkReportsCreateOrSupplementWorkReportData = {
    requestBody: WorkReportSubmit;
};

export type WorkReportsCreateOrSupplementWorkReportResponse = (WorkReportSubmissionResult);

export type WorkReportsReadReminderRulesResponse = (ReminderRulesPublic);

export type WorkReportsCreateReminderRuleData = {
    requestBody: ReminderRuleInput;
};

export type WorkReportsCreateReminderRuleResponse = (ReminderRulePublic);

export type WorkReportsUpdateReminderRuleData = {
    requestBody: ReminderRuleInput;
    ruleId: string;
};

export type WorkReportsUpdateReminderRuleResponse = (ReminderRulePublic);

export type WorkReportsDeleteReminderRuleData = {
    ruleId: string;
};

export type WorkReportsDeleteReminderRuleResponse = (Message);

export type WorkReportsTestReminderData = {
    requestBody: ReminderTestRequest;
};

export type WorkReportsTestReminderResponse = (ReminderTestResult);

export type WorkReportsReadReminderTestRecipientsResponse = (ReminderTestRecipientsPublic);

export type WorkReportsReadReminderRecipientsResponse = (ReminderRecipientsPublic);

export type WorkReportsReadReminderRunsData = {
    limit?: number;
    skip?: number;
};

export type WorkReportsReadReminderRunsResponse = (ReminderRunsPublic);

export type WorkReportsReadReminderUnboundUsersResponse = (ReminderUnboundUsersPublic);

export type WorkReportsReadReminderTimezonesResponse = (ReminderTimezonesPublic);

export type WorkReportsReadWorkReportData = {
    reportId: string;
};

export type WorkReportsReadWorkReportResponse = (WorkReportDetail);