"""add invoice_file table

Revision ID: 16583fefb912
Revises: b6a3b31a7cf9
Create Date: 2026-04-25 18:09:31.100482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '16583fefb912'
down_revision = 'b6a3b31a7cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_file',
        sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column('invoice_date', sa.Date(), nullable=False),
        sa.Column('invoice_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
        sa.Column('buyer', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('seller', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('invoice_type', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('owner_id', sa.Uuid(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('pdf_original_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('pdf_mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column('pdf_size', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_by_id', sa.Uuid(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['deleted_by_id'], ['user.id']),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_invoice_file_owner_invoice_number',
        'invoice_file',
        ['owner_id', 'invoice_number'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoice_file_owner_invoice_number', table_name='invoice_file')
    op.drop_table('invoice_file')
    # ### end Alembic commands ###
