"""add approved fields to invoice match

Revision ID: 1b77458a5968
Revises: 85dea52b034c
Create Date: 2026-05-05 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b77458a5968'
down_revision = '85dea52b034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_match', sa.Column('approved_by_id', sa.Uuid(), nullable=True))
    op.add_column('invoice_match', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'invoice_match', 'user', ['approved_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_match', type_='foreignkey')
    op.drop_column('invoice_match', 'approved_at')
    op.drop_column('invoice_match', 'approved_by_id')
    # ### end Alembic commands ###
