"""add contract_filled_version table

Revision ID: 24111d4e4226
Revises: 1b77458a5968
Create Date: 2026-06-20 08:36:08.535584

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '24111d4e4226'
down_revision = '1b77458a5968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_filled_version',
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('field_values', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=False),
    sa.Column('output_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('output_file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('output_file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_filled_version')
    # ### end Alembic commands ###
