"""add equipment_purchase_filled_version table

Revision ID: 59e6a99c56af
Revises: 24111d4e4226
Create Date: 2026-06-20 10:10:00.620263

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59e6a99c56af'
down_revision = '24111d4e4226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_purchase_filled_version',
    sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('field_values', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=False),
    sa.Column('equipment_items', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=True),
    sa.Column('output_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('output_file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('output_file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_purchase_filled_version')
    # ### end Alembic commands ###
