"""add_question_difficulty_and_device_type

Revision ID: 681f12f91687
Revises: d4e5f6a7b8c9
Create Date: 2026-06-05 06:16:45.601045

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '681f12f91687'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_index(op.f('idx_transaction_user_category'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_user_date'), table_name='transaction')
    op.drop_index(op.f('idx_transaction_user_type'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_constraint(op.f('fk_exam_paper_snapshot'), 'exam', type_='foreignkey')
    op.drop_column('exam', 'paper_snapshot_id')
    op.alter_column('exam_answer', 'selected_option_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_exam_answer_question_id'), table_name='exam_answer')
    op.drop_constraint(op.f('exam_answer_question_id_fkey'), 'exam_answer', type_='foreignkey')
    op.drop_constraint(op.f('exam_answer_attempt_id_fkey'), 'exam_answer', type_='foreignkey')
    op.create_foreign_key(None, 'exam_answer', 'exam_attempt', ['attempt_id'], ['id'])
    op.add_column('exam_attempt', sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.drop_index(op.f('ix_exam_attempt_exam_userid_status'), table_name='exam_attempt')
    op.drop_constraint(op.f('exam_attempt_exam_id_fkey'), 'exam_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'exam_attempt', 'exam', ['exam_id'], ['id'])
    op.alter_column('exam_paper_snapshot', 'snapshot_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('exam_paper_snapshot_exam_id_fkey'), 'exam_paper_snapshot', type_='foreignkey')
    op.create_foreign_key(None, 'exam_paper_snapshot', 'exam', ['exam_id'], ['id'])
    op.drop_constraint(op.f('fk_exam_participant_final_attempt'), 'exam_participant', type_='foreignkey')
    op.drop_constraint(op.f('exam_participant_exam_id_fkey'), 'exam_participant', type_='foreignkey')
    op.create_foreign_key(None, 'exam_participant', 'exam', ['exam_id'], ['id'])
    op.create_foreign_key(None, 'exam_participant', 'exam_attempt', ['final_attempt_id'], ['id'])
    op.add_column('question', sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.drop_constraint(op.f('question_exam_id_fkey'), 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'exam', ['exam_id'], ['id'])
    op.drop_constraint(op.f('question_option_question_id_fkey'), 'question_option', type_='foreignkey')
    op.create_foreign_key(None, 'question_option', 'question', ['question_id'], ['id'])
    op.drop_index(op.f('ix_sync_task_entity_type'), table_name='sync_task')
    op.drop_index(op.f('ix_sync_task_started_at'), table_name='sync_task')
    op.drop_constraint(op.f('sync_task_triggered_by_id_fkey'), 'sync_task', type_='foreignkey')
    op.create_foreign_key(None, 'sync_task', 'user', ['triggered_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sync_task', type_='foreignkey')
    op.create_foreign_key(op.f('sync_task_triggered_by_id_fkey'), 'sync_task', 'user', ['triggered_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_sync_task_started_at'), 'sync_task', ['started_at'], unique=False)
    op.create_index(op.f('ix_sync_task_entity_type'), 'sync_task', ['entity_type'], unique=False)
    op.drop_constraint(None, 'question_option', type_='foreignkey')
    op.create_foreign_key(op.f('question_option_question_id_fkey'), 'question_option', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key(op.f('question_exam_id_fkey'), 'question', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_column('question', 'difficulty')
    op.drop_constraint(None, 'exam_participant', type_='foreignkey')
    op.drop_constraint(None, 'exam_participant', type_='foreignkey')
    op.create_foreign_key(op.f('exam_participant_exam_id_fkey'), 'exam_participant', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_exam_participant_final_attempt'), 'exam_participant', 'exam_attempt', ['final_attempt_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'exam_paper_snapshot', type_='foreignkey')
    op.create_foreign_key(op.f('exam_paper_snapshot_exam_id_fkey'), 'exam_paper_snapshot', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.alter_column('exam_paper_snapshot', 'snapshot_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(None, 'exam_attempt', type_='foreignkey')
    op.create_foreign_key(op.f('exam_attempt_exam_id_fkey'), 'exam_attempt', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_exam_attempt_exam_userid_status'), 'exam_attempt', ['exam_id', 'userid', 'status'], unique=False)
    op.drop_column('exam_attempt', 'device_type')
    op.drop_constraint(None, 'exam_answer', type_='foreignkey')
    op.create_foreign_key(op.f('exam_answer_attempt_id_fkey'), 'exam_answer', 'exam_attempt', ['attempt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('exam_answer_question_id_fkey'), 'exam_answer', 'question', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_exam_answer_question_id'), 'exam_answer', ['question_id'], unique=False)
    op.alter_column('exam_answer', 'selected_option_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('exam', sa.Column('paper_snapshot_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_exam_paper_snapshot'), 'exam', 'exam_paper_snapshot', ['paper_snapshot_id'], ['id'], ondelete='SET NULL')
    op.create_table('transaction',
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'CNY'::character varying"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('transaction_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_pkey'))
    )
    op.create_index(op.f('idx_transaction_user_type'), 'transaction', ['user_id', 'type'], unique=False)
    op.create_index(op.f('idx_transaction_user_date'), 'transaction', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_transaction_user_category'), 'transaction', ['user_id', 'category'], unique=False)
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('test_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('item_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_pkey'))
    )
    # ### end Alembic commands ###
