"""add app_setting and reimbursement_export tables

Revision ID: 85dea52b034c
Revises: a4e06ea5ffad
Create Date: 2026-04-26 08:24:54.528517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '85dea52b034c'
down_revision = 'a4e06ea5ffad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('reimbursement_export',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('business_unit', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reimburser', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reimbursement_date', sa.Date(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('stored_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimbursement_export_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('export_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_record_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_file_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_match_id', sa.Uuid(), nullable=True),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('order_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('description_snapshot', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('department_snapshot', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['reimbursement_export.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_record_id'], ['purchase_record.id'], ),
    sa.ForeignKeyConstraint(['invoice_file_id'], ['invoice_file.id'], ),
    sa.ForeignKeyConstraint(['invoice_match_id'], ['invoice_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reimbursement_export_item')
    op.drop_table('reimbursement_export')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
