"""add level to wecom_department

Revision ID: d19e94f5d415
Revises: fe56fa70289e
Create Date: 2026-06-05 07:35:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = 'd19e94f5d415'
down_revision = '681f12f91687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wecom_department', sa.Column('level', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###

    # Compute level for existing records based on parentid hierarchy.
    # Root departments (parentid IS NULL or parentid = 0) are not assigned a
    # meaningful level here — their children get level 1 (center), grandchildren
    # get level 2 (department), anything deeper gets level 3 (invalid).
    conn = op.get_bind()

    # Fetch all existing departments
    rows = conn.execute(sa.text("SELECT id, parentid FROM wecom_department")).fetchall()
    dept_map = {row[0]: row[1] for row in rows}

    def compute_level(dept_id: int, visited: set | None = None) -> int:
        """Return hierarchy level for a department.

        Level rules:
        - Direct child of root (parentid IS NULL or 0) -> 1 (center)
        - Child of level 1 -> 2 (department)
        - Anything deeper -> 3 (invalid)
        """
        if visited is None:
            visited = set()
        if dept_id in visited:
            return 3  # cycle guard
        visited.add(dept_id)

        parent_id = dept_map.get(dept_id)
        if parent_id is None or parent_id == 0:
            return 0  # root itself — no meaningful level

        parent_level = compute_level(parent_id, visited.copy())
        if parent_level == 0:
            return 1
        elif parent_level == 1:
            return 2
        else:
            return 3

    # Batch update
    updates = []
    for dept_id in dept_map:
        lvl = compute_level(dept_id)
        updates.append((lvl, dept_id))

    if updates:
        conn.execute(
            sa.text("UPDATE wecom_department SET level = :level WHERE id = :id"),
            [{"level": lvl, "id": dept_id} for lvl, dept_id in updates],
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wecom_department', 'level')
    # ### end Alembic commands ###
