"""add wecom models

Revision ID: f3a9c2b1d4e5
Revises: 8bf59a1e7457
Create Date: 2025-05-27 10:00:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'f3a9c2b1d4e5'
down_revision = '8bf59a1e7457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wecomconfig',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('corp_id', sa.String(length=64), nullable=False),
        sa.Column('agent_id', sa.String(length=64), nullable=False),
        sa.Column('secret_encrypted', sa.String(length=255), nullable=False),
        sa.Column('trusted_domain', sa.String(length=255), nullable=True),
        sa.Column('access_token', sa.String(length=512), nullable=True),
        sa.Column('access_token_expire_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemuserrole',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('userid', sa.String(length=64), nullable=False),
        sa.Column('role_code', sa.String(length=64), nullable=False),
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemuserrole_userid'), 'systemuserrole', ['userid'], unique=False)
    op.add_column('user', sa.Column('wecom_userid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_wecom_userid'), 'user', ['wecom_userid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wecom_userid'), table_name='user')
    op.drop_column('user', 'wecom_userid')
    op.drop_index(op.f('ix_systemuserrole_userid'), table_name='systemuserrole')
    op.drop_table('systemuserrole')
    op.drop_table('wecomconfig')
    # ### end Alembic commands ###
