/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOkrRouteImport } from './routes/_layout/okr'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LoginFeishuCallbackRouteImport } from './routes/login_.feishu.callback'
import { Route as LayoutOkrPeopleBoardRouteImport } from './routes/_layout/okr.people-board'
import { Route as LayoutOkrMyRouteImport } from './routes/_layout/okr.my'
import { Route as LayoutOkrDepartmentsRouteImport } from './routes/_layout/okr.departments'
import { Route as LayoutOkrDepartmentBoardRouteImport } from './routes/_layout/okr.department-board'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOkrRoute = LayoutOkrRouteImport.update({
  id: '/okr',
  path: '/okr',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LoginFeishuCallbackRoute = LoginFeishuCallbackRouteImport.update({
  id: '/login_/feishu/callback',
  path: '/login/feishu/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutOkrPeopleBoardRoute = LayoutOkrPeopleBoardRouteImport.update({
  id: '/people-board',
  path: '/people-board',
  getParentRoute: () => LayoutOkrRoute,
} as any)
const LayoutOkrMyRoute = LayoutOkrMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => LayoutOkrRoute,
} as any)
const LayoutOkrDepartmentsRoute = LayoutOkrDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => LayoutOkrRoute,
} as any)
const LayoutOkrDepartmentBoardRoute =
  LayoutOkrDepartmentBoardRouteImport.update({
    id: '/department-board',
    path: '/department-board',
    getParentRoute: () => LayoutOkrRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/okr': typeof LayoutOkrRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/okr/department-board': typeof LayoutOkrDepartmentBoardRoute
  '/okr/departments': typeof LayoutOkrDepartmentsRoute
  '/okr/my': typeof LayoutOkrMyRoute
  '/okr/people-board': typeof LayoutOkrPeopleBoardRoute
  '/login/feishu/callback': typeof LoginFeishuCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/okr': typeof LayoutOkrRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/okr/department-board': typeof LayoutOkrDepartmentBoardRoute
  '/okr/departments': typeof LayoutOkrDepartmentsRoute
  '/okr/my': typeof LayoutOkrMyRoute
  '/okr/people-board': typeof LayoutOkrPeopleBoardRoute
  '/login/feishu/callback': typeof LoginFeishuCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/okr': typeof LayoutOkrRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/okr/department-board': typeof LayoutOkrDepartmentBoardRoute
  '/_layout/okr/departments': typeof LayoutOkrDepartmentsRoute
  '/_layout/okr/my': typeof LayoutOkrMyRoute
  '/_layout/okr/people-board': typeof LayoutOkrPeopleBoardRoute
  '/login_/feishu/callback': typeof LoginFeishuCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/okr'
    | '/settings'
    | '/okr/department-board'
    | '/okr/departments'
    | '/okr/my'
    | '/okr/people-board'
    | '/login/feishu/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/okr'
    | '/settings'
    | '/'
    | '/okr/department-board'
    | '/okr/departments'
    | '/okr/my'
    | '/okr/people-board'
    | '/login/feishu/callback'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/okr'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/okr/department-board'
    | '/_layout/okr/departments'
    | '/_layout/okr/my'
    | '/_layout/okr/people-board'
    | '/login_/feishu/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LoginFeishuCallbackRoute: typeof LoginFeishuCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/okr': {
      id: '/_layout/okr'
      path: '/okr'
      fullPath: '/okr'
      preLoaderRoute: typeof LayoutOkrRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/login_/feishu/callback': {
      id: '/login_/feishu/callback'
      path: '/login/feishu/callback'
      fullPath: '/login/feishu/callback'
      preLoaderRoute: typeof LoginFeishuCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/okr/people-board': {
      id: '/_layout/okr/people-board'
      path: '/people-board'
      fullPath: '/okr/people-board'
      preLoaderRoute: typeof LayoutOkrPeopleBoardRouteImport
      parentRoute: typeof LayoutOkrRoute
    }
    '/_layout/okr/my': {
      id: '/_layout/okr/my'
      path: '/my'
      fullPath: '/okr/my'
      preLoaderRoute: typeof LayoutOkrMyRouteImport
      parentRoute: typeof LayoutOkrRoute
    }
    '/_layout/okr/departments': {
      id: '/_layout/okr/departments'
      path: '/departments'
      fullPath: '/okr/departments'
      preLoaderRoute: typeof LayoutOkrDepartmentsRouteImport
      parentRoute: typeof LayoutOkrRoute
    }
    '/_layout/okr/department-board': {
      id: '/_layout/okr/department-board'
      path: '/department-board'
      fullPath: '/okr/department-board'
      preLoaderRoute: typeof LayoutOkrDepartmentBoardRouteImport
      parentRoute: typeof LayoutOkrRoute
    }
  }
}

interface LayoutOkrRouteChildren {
  LayoutOkrDepartmentBoardRoute: typeof LayoutOkrDepartmentBoardRoute
  LayoutOkrDepartmentsRoute: typeof LayoutOkrDepartmentsRoute
  LayoutOkrMyRoute: typeof LayoutOkrMyRoute
  LayoutOkrPeopleBoardRoute: typeof LayoutOkrPeopleBoardRoute
}

const LayoutOkrRouteChildren: LayoutOkrRouteChildren = {
  LayoutOkrDepartmentBoardRoute: LayoutOkrDepartmentBoardRoute,
  LayoutOkrDepartmentsRoute: LayoutOkrDepartmentsRoute,
  LayoutOkrMyRoute: LayoutOkrMyRoute,
  LayoutOkrPeopleBoardRoute: LayoutOkrPeopleBoardRoute,
}

const LayoutOkrRouteWithChildren = LayoutOkrRoute._addFileChildren(
  LayoutOkrRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutOkrRoute: typeof LayoutOkrRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutOkrRoute: LayoutOkrRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LoginFeishuCallbackRoute: LoginFeishuCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
