/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthWecomCallbackRouteImport } from './routes/auth/wecom-callback'
import { Route as LayoutWecomMemberSyncRouteImport } from './routes/_layout/wecom-member-sync'
import { Route as LayoutWecomDepartmentSyncRouteImport } from './routes/_layout/wecom-department-sync'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMyExamsRouteImport } from './routes/_layout/my-exams'
import { Route as LayoutExamsRouteImport } from './routes/_layout/exams'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutExamsIndexRouteImport } from './routes/_layout/exams/index'
import { Route as LayoutMyExamsExamIdRouteImport } from './routes/_layout/my-exams/$examId'
import { Route as LayoutExamsNewRouteImport } from './routes/_layout/exams/new'
import { Route as LayoutExamsExamIdRouteImport } from './routes/_layout/exams/$examId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthWecomCallbackRoute = AuthWecomCallbackRouteImport.update({
  id: '/auth/wecom-callback',
  path: '/auth/wecom-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWecomMemberSyncRoute = LayoutWecomMemberSyncRouteImport.update({
  id: '/wecom-member-sync',
  path: '/wecom-member-sync',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWecomDepartmentSyncRoute =
  LayoutWecomDepartmentSyncRouteImport.update({
    id: '/wecom-department-sync',
    path: '/wecom-department-sync',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMyExamsRoute = LayoutMyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsRoute = LayoutExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExamsIndexRoute = LayoutExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutExamsRoute,
} as any)
const LayoutMyExamsExamIdRoute = LayoutMyExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => LayoutMyExamsRoute,
} as any)
const LayoutExamsNewRoute = LayoutExamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutExamsRoute,
} as any)
const LayoutExamsExamIdRoute = LayoutExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => LayoutExamsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/exams': typeof LayoutExamsRouteWithChildren
  '/my-exams': typeof LayoutMyExamsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/wecom-department-sync': typeof LayoutWecomDepartmentSyncRoute
  '/wecom-member-sync': typeof LayoutWecomMemberSyncRoute
  '/auth/wecom-callback': typeof AuthWecomCallbackRoute
  '/exams/$examId': typeof LayoutExamsExamIdRoute
  '/exams/new': typeof LayoutExamsNewRoute
  '/my-exams/$examId': typeof LayoutMyExamsExamIdRoute
  '/exams/': typeof LayoutExamsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/my-exams': typeof LayoutMyExamsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/wecom-department-sync': typeof LayoutWecomDepartmentSyncRoute
  '/wecom-member-sync': typeof LayoutWecomMemberSyncRoute
  '/auth/wecom-callback': typeof AuthWecomCallbackRoute
  '/': typeof LayoutIndexRoute
  '/exams/$examId': typeof LayoutExamsExamIdRoute
  '/exams/new': typeof LayoutExamsNewRoute
  '/my-exams/$examId': typeof LayoutMyExamsExamIdRoute
  '/exams': typeof LayoutExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/exams': typeof LayoutExamsRouteWithChildren
  '/_layout/my-exams': typeof LayoutMyExamsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/wecom-department-sync': typeof LayoutWecomDepartmentSyncRoute
  '/_layout/wecom-member-sync': typeof LayoutWecomMemberSyncRoute
  '/auth/wecom-callback': typeof AuthWecomCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/exams/$examId': typeof LayoutExamsExamIdRoute
  '/_layout/exams/new': typeof LayoutExamsNewRoute
  '/_layout/my-exams/$examId': typeof LayoutMyExamsExamIdRoute
  '/_layout/exams/': typeof LayoutExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/exams'
    | '/my-exams'
    | '/settings'
    | '/wecom-department-sync'
    | '/wecom-member-sync'
    | '/auth/wecom-callback'
    | '/exams/$examId'
    | '/exams/new'
    | '/my-exams/$examId'
    | '/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/my-exams'
    | '/settings'
    | '/wecom-department-sync'
    | '/wecom-member-sync'
    | '/auth/wecom-callback'
    | '/'
    | '/exams/$examId'
    | '/exams/new'
    | '/my-exams/$examId'
    | '/exams'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/exams'
    | '/_layout/my-exams'
    | '/_layout/settings'
    | '/_layout/wecom-department-sync'
    | '/_layout/wecom-member-sync'
    | '/auth/wecom-callback'
    | '/_layout/'
    | '/_layout/exams/$examId'
    | '/_layout/exams/new'
    | '/_layout/my-exams/$examId'
    | '/_layout/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthWecomCallbackRoute: typeof AuthWecomCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/wecom-callback': {
      id: '/auth/wecom-callback'
      path: '/auth/wecom-callback'
      fullPath: '/auth/wecom-callback'
      preLoaderRoute: typeof AuthWecomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/wecom-member-sync': {
      id: '/_layout/wecom-member-sync'
      path: '/wecom-member-sync'
      fullPath: '/wecom-member-sync'
      preLoaderRoute: typeof LayoutWecomMemberSyncRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/wecom-department-sync': {
      id: '/_layout/wecom-department-sync'
      path: '/wecom-department-sync'
      fullPath: '/wecom-department-sync'
      preLoaderRoute: typeof LayoutWecomDepartmentSyncRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/my-exams': {
      id: '/_layout/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof LayoutMyExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams': {
      id: '/_layout/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof LayoutExamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exams/': {
      id: '/_layout/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof LayoutExamsIndexRouteImport
      parentRoute: typeof LayoutExamsRoute
    }
    '/_layout/my-exams/$examId': {
      id: '/_layout/my-exams/$examId'
      path: '/$examId'
      fullPath: '/my-exams/$examId'
      preLoaderRoute: typeof LayoutMyExamsExamIdRouteImport
      parentRoute: typeof LayoutMyExamsRoute
    }
    '/_layout/exams/new': {
      id: '/_layout/exams/new'
      path: '/new'
      fullPath: '/exams/new'
      preLoaderRoute: typeof LayoutExamsNewRouteImport
      parentRoute: typeof LayoutExamsRoute
    }
    '/_layout/exams/$examId': {
      id: '/_layout/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof LayoutExamsExamIdRouteImport
      parentRoute: typeof LayoutExamsRoute
    }
  }
}

interface LayoutExamsRouteChildren {
  LayoutExamsExamIdRoute: typeof LayoutExamsExamIdRoute
  LayoutExamsNewRoute: typeof LayoutExamsNewRoute
  LayoutExamsIndexRoute: typeof LayoutExamsIndexRoute
}

const LayoutExamsRouteChildren: LayoutExamsRouteChildren = {
  LayoutExamsExamIdRoute: LayoutExamsExamIdRoute,
  LayoutExamsNewRoute: LayoutExamsNewRoute,
  LayoutExamsIndexRoute: LayoutExamsIndexRoute,
}

const LayoutExamsRouteWithChildren = LayoutExamsRoute._addFileChildren(
  LayoutExamsRouteChildren,
)

interface LayoutMyExamsRouteChildren {
  LayoutMyExamsExamIdRoute: typeof LayoutMyExamsExamIdRoute
}

const LayoutMyExamsRouteChildren: LayoutMyExamsRouteChildren = {
  LayoutMyExamsExamIdRoute: LayoutMyExamsExamIdRoute,
}

const LayoutMyExamsRouteWithChildren = LayoutMyExamsRoute._addFileChildren(
  LayoutMyExamsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExamsRoute: typeof LayoutExamsRouteWithChildren
  LayoutMyExamsRoute: typeof LayoutMyExamsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWecomDepartmentSyncRoute: typeof LayoutWecomDepartmentSyncRoute
  LayoutWecomMemberSyncRoute: typeof LayoutWecomMemberSyncRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExamsRoute: LayoutExamsRouteWithChildren,
  LayoutMyExamsRoute: LayoutMyExamsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWecomDepartmentSyncRoute: LayoutWecomDepartmentSyncRoute,
  LayoutWecomMemberSyncRoute: LayoutWecomMemberSyncRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthWecomCallbackRoute: AuthWecomCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
